### ISSUE TITLE
fix docker compose file

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/onboarding-web#85]
It should be self-explanatory how to get a local environment up-and-running:

DoD:
- [x] update the readme with the port and URL to be used localhost:3000/onboarding
- [x] include facility or describe how to load the test data set (playgrounds)
- [x] spin up mysql instead of axondb

**Comment by errrrk** [comment]
As extra info to this task:
- During development port 80 is typically avoided due to elevated privileges and conflicts with other running processes. On AWS we're not allowed to run on port 80. So I guess the question is, why does it need to be port 80?
- This is not part of docker-compose file, instead it's programmed into `onboarding-web`. Coordinate with Gerard or Dylan to get this done.
- Spinning up Mysql is currently part of our development efforts to get the application rolling on AWS. It's on the `axon_mysql` branch, see here https://github.com/local-motion/bootstrap/blob/axon_mysql/development/docker-compose.yml and https://github.com/local-motion/smokefree-initiative-service/blob/axon_mysql/src/main/java/smokefree/AxonFactory.java#L69. 
We could merge the 'mysql on local'-change ahead of time, but I'm not sure if that has benefits.
